service: serverless-ts
provider:
  name: aws
  runtime: nodejs4.3
  iamRoleStatements:
  - Effect: Allow
    Action:
    - lambda:ListFunctions
    Resource: "*"
plugins:
- serverless-webpack
functions:
  hello:
    handler: index.hello
    events:
    - http:
        path: hello
        method: get
  listfunctions:
    handler: index.listfunctions
    events:
    - http:
        path: listfunctions
        method: get
